name: 'Clean Up Workspace'
description: 'Cleans up the workspace after build finishes'
author: 'git9527'
branding:
  icon: 'delete'
  color: 'red'
inputs:
  keepGit:
    description: 'Keep the .git folder to speedup cloning'
    required: false
runs:
  using: 'node20'
  main: 'index.js'
  post: 'cleanup.js'
